### ISSUE TITLE
dead links in build guide

### ISSUE THREAD

**Issue by teppeis** [hanachi-ap/ergotonic_f24#1]
いくつかリンク切れを見つけたので報告します。

[遊舎工房(ロータリーエンコーダ(ノブ付き)](https://shop.yushakobo.jp/collections/keyboard-parts/products/pec12r-4222f-s0024)
https://github.com/hanachi-ap/ergotonic_f24/blob/006d9dbf5f218238c52e51f8aaa2f3123f591980/docs/01_preparation.md

ゆかりキーボードファクトリ https://eucalyn.shop/
https://github.com/hanachi-ap/ergotonic_f24/blob/006d9dbf5f218238c52e51f8aaa2f3123f591980/docs/08_reference.md

チートシート [keymap_cheatsheet_ergotonic_49.pdf](img/keymap_cheatsheet_ergotonic_49.pdf)
https://github.com/hanachi-ap/ergotonic_f24/blob/006d9dbf5f218238c52e51f8aaa2f3123f591980/docs/09_customize.md

**Comment by hanachi-ap** [comment]
@teppeis  指摘ありがとうございます。各リンク修正しました (チートシートは記事から削除)
